name: Validate Infra

on:
  workflow_dispatch:

env:
  TERRAFORM_VERSION: 1.12.1
  TERRAFORM_DIR: infra

jobs:
  # JOB 1: Setup AWS and install Terraform
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Test AWS Connection (Get Caller Identity)
        run: |
          aws sts get-caller-identity

      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/${{ env.TERRAFORM_VERSION }}/terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
          unzip terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

      - name: Change directory to infra
        run: |
          cd ${{ env.TERRAFORM_DIR }}
          terraform init
          terraform validate
          terraform plan \
          -var="deep_seek_api_key=${{ secrets.DEEPSEEK_API_KEY }}" \
          -var="region=${{ secrets.AWS_REGION }}"